# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed752c67cf810699250bc0fe2c83e1cfc8035e03119c8b7bd1f5088868e00048e49353af1072571928148554a79b3f2af27835ceff2489c94575046049740e78

test:
  secret_key_base: 2193a5c94a6a85f60ba44bfefa1e8e0157edce96df4bcb1de99ee4b01b6763662659fae84a8b9a14aca34a62a614f84651e75413f003b80e2b33584e84a571dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
